### PR TITLE
Whatsapp msg

### PR DESCRIPTION
**Pull request by sudipg4112001**
# Whatsapp Message send

A python script through which message can be scheduled on a particular time to a particular mobile number with particular text.

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
You should add more features and modify this project .

**Comment by sudipg4112001** [comment]
> You should add more features and modify this project .

I don't find any more features to add here. Please suggest if you have any.

**Comment by Mrinank-Bhowmick** [comment]
Explore from google

**Review by David-hosting — APPROVED** [review]
Well written and easy to understand!

**Pull request closed without merging**
