### PR TITLE
Added a Calendar program

### PR DESCRIPTION
**Pull request by snehafarkya**
# Addition of a small project

- [x] Added new project

# Changes proposed in this pull request

* ### Project name : Calendar

* ### Short description :  This is a python project which takes year and month as input and displays the calendar.

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by snehafarkya** [comment]
Hey @Mrinank-Bhowmick ! Can you add the `hactoberfest` and `hacktoberfest-accepted` tag on this?

**Review by Mrinank-Bhowmick — CHANGES_REQUESTED** [review]
Hey @snehafarkya , this is a very very small program . You may not get approved for hacktoberfest contribution. 
Please add more features to it.

**Comment by snehafarkya** [comment]
> Hey @snehafarkya , this is a very very small program . You may not get approved for hacktoberfest contribution. Please add more features to it.

Hey @Mrinank-Bhowmick ! I have added a game called Roll-A-Dice. It will give you random questions and save your answer in the database.

### Code: 

image

### Result: 

image

**Comment by Mrinank-Bhowmick** [comment]
Looks good 
Thank you 👍

**Review by Mrinank-Bhowmick — COMMENTED** [review]
Good 👍

**Pull request merged**
