### PR TITLE
Add Othello/Reversi GUI Game

### PR DESCRIPTION
**Pull request by TERNION-1121**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :
Othello

* ### Short description : 
Othello Game (GUI equipped); Made using numpy and pygame.
## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Hey @TERNION-1121 
This project looks awesome 💯 
I will accept this pr after 1st October so that it comes under hacktoberfest contribution

**Comment by TERNION-1121** [comment]
> Hey @TERNION-1121 This project looks awesome 💯 I will accept this pr after 1st October so that it comes under hacktoberfest contribution

Hello there @Mrinank-Bhowmick! Thanks for your kind words :)
I have worked more on this project, I shall be committing those changes as well....

Excited for Hacktoberfest :D

**Comment by Mrinank-Bhowmick** [comment]
Comment here when its done 👍

**Comment by TERNION-1121** [comment]
> Comment here when its done 👍

Hey @Mrinank-Bhowmick! Thanks for waiting :)
I've done everything I could've thought of for this project.
You may review the code once again, and let me know about any final changes/ suggestions for the codebase or README...

That's all from my side 
Thanks!

**Comment by Mrinank-Bhowmick** [comment]
Looks good to me 👍 
Happy Hacktoberfest ⭐

**Pull request merged**
