### PR TITLE
Big Comeback with load of script.

### PR DESCRIPTION
**Pull request by ibra-kdbra**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [x] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : chore-assignment-emailer
* ### Project name : coin-toss
* ### Project name : comma-code
* ### Project name : custom-seating-cards
* ### Project name : custom-invitations
* ### Project name : excel-to-csv-convertor
* ### Project name : fantasy-game-inventory
* ### Project name : fill-gaps
* ### Project name : find-unneeded-files
* ### Project name : image-site-downloader
* ### Project name : instant-messanger-bot
* ### Project name : link-verification
* ### Project name : looking-busy
* ### Project name : mad-libs

#### After five days added more projects:
* ### Project name :Comics_Scraper
* ### Project name :Text_to_SpreadSheet
* ### Project name :WorkSheet_to_text

* ### Short description : too much projects to describe, they are just simple automated scripts for your daily boring life, I am adding more generative code and AI simple things, hope for the best

#### After five days:
* ### Short description : excel sheet to text and backword, comics scraper from xkcd.com

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by ibra-kdbra** [comment]
What happened for this PR, Is there anything wrong that I can help with?

**Comment by Mrinank-Bhowmick** [comment]
@ibra-kdbra Sorry for the delay 😄 
Thanks for adding so many of them but
some projects are already there like madliibs, coin flip etc, so need to remove them.

**Comment by ibra-kdbra** [comment]
No problem, no need to hurry, thanks for replying.
If you want any help in issues or PR in this repo, I'm all for it.

**Comment by ibra-kdbra** [comment]
done

**Comment by Mrinank-Bhowmick** [comment]
Thanks for the contributions, they are really unique and great 🔥

**Pull request merged**
