### PR TITLE
Ibra kdbra

### PR DESCRIPTION
**Pull request by ibra-kdbra**
# Type of change 

- [x] Added new project
- [x] Bug fix
- [x] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :
- BitTorrent-downloader
- character-picture-grid
- image-to-pdf-convertor
- regex-strip
- regex-search
- Passwords-projects: feature: strong password detector
- pdf-paranoia
- prettified-stopwatch
- Reuters-scraper
- Reddit-scraper
- regex-search

* ### Short description : 
I'm too lazy to write the description, sorry.., every commit has some degree of description.
## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make the code understandable
- [x] I have added my project to a folder that includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Thank you for your valuable contributions to the repository!
Your added Python projects are greatly appreciated and add significant value to the community. 
Keep up the great work!

**Comment by ibra-kdbra** [comment]
I am adding some projects on generative AI and some basic artificial AI, should I make a specific folder for this so users or followers won't get lost?

To be honest the scraping projects I add before is also part of NLP(natural language processing) that you already know is big part of AI today.

Any recommendation would help.

**Comment by Mrinank-Bhowmick** [comment]
Ya that would be better.
Make a specific folder for Generative AI, then we can make a separate section in readme file for Generative AI contents.

**Comment by ibra-kdbra** [comment]
To be clear, this directory should be inside _projects_ directory or make it outside?

And add the generative **AI** _projects_ with the simple **AI** _projects_?

**Comment by Mrinank-Bhowmick** [comment]
What do you think ? 👀

**Pull request merged**
