### PR TITLE
Added new Project Song Lyrics Extractor

### PR DESCRIPTION
**Pull request by sirKiraUzumaki**
# Type of change 

- [ Yes] Added new project

# Changes proposed in this pull request

* ### Project name :
Lyrics Extractor

* ### Short description : 
Extract lyrics in terminal using python
## Checklist

- [Yes] The code is Python 3 compatible
- [Yes ] I have added relevant comments in my file to make code understandable
- [Yes] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by sirKiraUzumaki** [comment]
What's wrong with the check? @Mrinank-Bhowmick

**Comment by Mrinank-Bhowmick** [comment]
> What's wrong with the check? @Mrinank-Bhowmick

Dont worry about that

**Comment by sirKiraUzumaki** [comment]
oh thanks
btw when you will merged it?

**Comment by Mrinank-Bhowmick** [comment]
> oh thanks btw when you will merged it?

after you make those changes which I requested for

**Comment by sirKiraUzumaki** [comment]
No conflicts and I don't see any task or changes from your side... Can you merge it please

**Comment by Mrinank-Bhowmick** [comment]
> No conflicts and I don't see any task or changes from your side... Can you merge it please

please read the requested review above

**Comment by sirKiraUzumaki** [comment]
> > No conflicts and I don't see any task or changes from your side... Can you merge it please
> 
> please read the requested review above

bro I don't see any review requested from your side 😭.. please check again

**Pull request merged**
