### PR TITLE
Created calculator using pyhon

### PR DESCRIPTION
**Pull request by shubham7668**
Created a GUI for calculations using tkinter library in python

# Type of change 

- [ ] Added new project
- [ ] Bug fix
- [x] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :

* ### Short description : 

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by shubham7668** [comment]
Hey @Mrinank-Bhowmick 
Could you please check!

**Comment by Mrinank-Bhowmick** [comment]
Looks good , thanks for contributing 👍

**Comment by shubham7668** [comment]
> Looks good , thanks for contributing 👍
Could you please add hacktoberfest's label :)

**Comment by Mrinank-Bhowmick** [comment]
sure

**Pull request merged**
