### PR TITLE
Audio Captcha Generator

### PR DESCRIPTION
**Pull request by parth-verma7**
# Audio Captcha Generator

Added a new functionality of Generating Captcha using Audio.
pygame
captcha
tkinter

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Thanks for contributing ⭐ 
#327 

But try to make a pr for one issue at a time as it may consider spam for hacktoberfest , so I am removing your expense-tracker commit

**Comment by parth-verma7** [comment]
> Thanks for contributing ⭐ #327
> 
> But try to make a pr for one issue at a time as it may consider spam for hacktoberfest , so I am removing your expense-tracker commit

Thanks a lot @Mrinank-Bhowmick I will consider it.

**Comment by Mrinank-Bhowmick** [comment]
Hey can you recommit it by removing your expense-tracker part

**Comment by parth-verma7** [comment]
> Hey can you recommit it by removing your expense-tracker part

okay

**Comment by parth-verma7** [comment]
> Hey can you recommit it by removing your expense-tracker part

Have a look please.

**Pull request closed without merging**
