### PR TITLE
new project added

### PR DESCRIPTION
**Pull request by sumitbaroniya**
# Type of change 

- [X] Added new project

# Changes proposed in this pull request

* ### Project name :
- Sudoku-Solver

* ### Short description : 
 Sudoku Solver helps you to solve almost any Sudoku Puzzle by visualizing through the Backtracking Algorithm. We can use this logic to get its solution instantly and move further.
## Checklist

- [X] The code is Python 3 compatible
- [X] I have added relevant comments in my file to make code understandable
- [X] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by MonitSharma** [comment]
> # Type of change
> * [x]  Added new project
> 
> # Changes proposed in this pull request
> * ### Project name : Sudoku-Solver
> 
> 
> 
> * ### Short description :  Sudoku Solver helps you to solve almost any Sudoku Puzzle by visualizing through the Backtracking Algorithm. We can use this logic to get its solution instantly and move further.
> 
>
> 
> ## Checklist
> * [x]  The code is Python 3 compatible
> * [x]  I have added relevant comments in my file to make code understandable
> * [x]  I have added my project in a folder which includes all the necessary files


HI @sumitbaroniya 

Add "x" between the "[ ]" brackets  , that will help to get the markdown sorted quickly as what you've done in the project. It basically checks the check box.
The file will look like this. You can also go through [this](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet) as it will tell you how you can work with the markdown files.

**Comment by sumitbaroniya** [comment]
@MonitSharma done. I have checked all the boxes

**Comment by sumitbaroniya** [comment]
@MonitSharma done.
Thank you so much for your guidance.

**Comment by sumitbaroniya** [comment]
Please merge it

**Comment by Mrinank-Bhowmick** [comment]
Looks good , thanks for contributing 👍

**Pull request merged**
