### PR TITLE
Text to Speech

### PR DESCRIPTION
**Pull request by sudipg4112001**
# Type of change 

- [x] Added new project
- [x] Bug fix
- [x] New features 
- [x] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : Text to Speech

* ### Short description : The python script takes text as input and then gives output in form of audio of the respective text. 

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by glacias07** [comment]
Hi @sudipg4112001, can you also add speech to text. I am looking for a simpler version to integrate it into one of my own side projects.

**Comment by Mrinank-Bhowmick** [comment]
> Hi @sudipg4112001 great work, can you also add speech to text. I am looking for a simpler version to integrate it into one of my own side projects.

https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Voice-to-Text
Here is speech to text program . 
If you want to modify this then let me know.

**Comment by Mrinank-Bhowmick** [comment]
> # Type of change
> * [x]  Added new project
> * [x]  Bug fix
> * [x]  New features
> * [x]  Enhanced documentation
> 
> # Changes proposed in this pull request
> * ### Project name : Text to Speech
> * ### Short description : The python script takes text as input and then gives output in form of audio of the respective text.
> 
> ## Checklist
> * [x]  The code is Python 3 compatible
> * [x]  I have added relevant comments in my file to make code understandable
> * [x]  I have added my project in a folder which includes all the necessary files

Looks good! Thank you. 🚀

**Comment by Mrinank-Bhowmick** [comment]
> > > Hi @sudipg4112001 great work, can you also add speech to text. I am looking for a simpler version to integrate it into one of my own side projects.
> > 
> > 
> > https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/projects/Voice-to-Text Here is speech to text program . If you want to modify this then let me know.
> 
> Looks exactly what I needed. I will try integrating it in my software.

Cool 👍

**Pull request merged**
