### PR TITLE
Added a new project: ToDoList

### PR DESCRIPTION
**Pull request by otahina**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : ToDoList

* ### Short description :  This is a simple command-line ToDo List application written in Python.

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Hey @otahina 👋 
Dont have to change any configurations in the GitHub actions. It's automated and tested 🚀 . 
[this folder --> .github/](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/.github)

**Comment by otahina** [comment]
Hi! Thank you for telling me. 😀 I wanted to add a new project, and it wasn't my intention to change any GitHub actions, but now I don't know how to remove these commits other than adding a new project. I would appreciate it if you could teach me how to undo them. 🙏

**Comment by otahina** [comment]
I think I could remove other commits than adding a new project! Could you check it out?

**Comment by Mrinank-Bhowmick** [comment]
Yeah now its removed 👍

**Pull request merged**
