### PR TITLE
added my python space battle game project

### PR DESCRIPTION
**Pull request by Sanket-0510**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :

* ### Short description : 

## Checklist

- [x] The code is Python 3 compatible
- [ ] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Sanket-0510** [comment]
ProjectName: space_battle 
its a python game made using pygame library in python.

**Comment by Mrinank-Bhowmick** [comment]
Hey @Sanket-0510 ,  it looks good to me ⭐
Thanks for your contribution 🚀

**Comment by Sanket-0510** [comment]
May I know what error is my merge request facing

**Comment by Mrinank-Bhowmick** [comment]
Basically it was github actions error, this project is using linters

**Pull request merged**
