### PR TITLE
Image Toonifier

### PR DESCRIPTION
**Pull request by Logadheep**
# Type of change 

- [x] Added new project
- [x] New features 
- [x] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : Image Toonification

* ### Short description : A script or App to apply cartoon effect to the given image.

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Let me know we its done

**Comment by Logadheep** [comment]
Sure

**Comment by Logadheep** [comment]
Can you please help with this. I can not understand the issue here!

**Comment by Mrinank-Bhowmick** [comment]
> Can you please help with this. I can not understand the issue here!

about the checks and workflows?

**Comment by Mrinank-Bhowmick** [comment]
I think its completed merging it 👍

**Pull request merged**
