### PR TITLE
Machine_Learning_Beginner_Guide

### PR DESCRIPTION
**Pull request by ibra-kdbra**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [x] New features 
- [x] Enhanced documentation

# Changes proposed in this pull request

* ### Directory name : ML-notebooks_Beginners/

* ### Short description : Basic three jupyter notebooks on math:
* algebra * Mean finder * Feature Scaling

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant markdowns in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
Hey @ibra-kdbra ,
I am not accepting .ipynb files anymore as it affects SEO of the repository.
image

**Comment by ibra-kdbra** [comment]
Okay, I will try to make these to Python files and then call them one by one if that suits you..

**Comment by Mrinank-Bhowmick** [comment]
Ya sure that would be better

**Comment by ibra-kdbra** [comment]
About the notebooks, it's inappropriate for me to make them as a **Python** file, because the notes in the markdowns text are critical, and visualizing the graphs is also essential/crucial, this will not be very user-friendly, if it's made in **Python** script, making comments, using **OpenCV** instead of _matplotlib_, this will need to save every image, it will take more time, more code less value, so I decide to make another **basic script** that don't contain anything about AI...

**Comment by Mrinank-Bhowmick** [comment]
But if the codes will be larger then Jupyter Notebook percentage will overcome python percentage

**Comment by ibra-kdbra** [comment]
Did you read my last comment, I told I removed jupyter notebooks

**Comment by Mrinank-Bhowmick** [comment]
image

But ig this will still affect the percentage

**Comment by ibra-kdbra** [comment]
So what should, I do now?

**Comment by Mrinank-Bhowmick** [comment]
You should try markdown format.
Include your code within ```
```python
print('Hello world') 
```

**Comment by ibra-kdbra** [comment]
Can you elaborate more?

**Comment by Mrinank-Bhowmick** [comment]
Make a detailed guide.md file
Then include all your python codes between (```python ``) these tags.
You can also include headings, summaries, code etc in markdown format. 

Example:
image

```python
print("Hello world")
```

**Comment by ibra-kdbra** [comment]
Is this for using Jupyter notebooks inside the file 'Guide.md'?

**Comment by Mrinank-Bhowmick** [comment]
yes @mrinank you can find me in python discord server

**Pull request merged**
