### PR TITLE
advik-student-dev 'Tennis Tournament Simulation' commits

### PR DESCRIPTION
**Pull request by advik-student-dev**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :
TennisTournamentSim

* ### Short description : 

A tennis tournament simulation which creates random people from a class which calls random names and schools of those 'people' from a test. 
Makes use of constants, functions, and classes. 
Bracket System - Bracket 1 Round 1, Bracket 2 Round 1, Finals (only 4 because I couldn't figure out how to make a recallable function for the bracket maker, probably could make it if I tried, but it seemed too overkill for something like this).
 
*### Code Environment :

Written in Pycharm
Virtual environment folder is already inside this folder. 
Shouldn't cause any problems.
I have my own repository for it.

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make code understandable
- [x] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by advik-student-dev** [comment]
lost my sanity while writing the finals brackets

**Comment by advik-student-dev** [comment]
@iamkunalpitale 
is this good?

**Comment by Mrinank-Bhowmick** [comment]
What is .DS_Store file ?

**Comment by advik-student-dev** [comment]
idk
i think it is a macos only file?

**Comment by Mrinank-Bhowmick** [comment]
> idk i think it is a macos only file?

So please remove those files from the commit

**Pull request closed without merging**
