### PR TITLE
Create new repository banner

### PR DESCRIPTION
**Pull request by TERNION-1121**
Hi @Mrinank-Bhowmick 
Good evening!

I thought of coming up with a new design for the repository banner.
So.. I came up with this:

new-banner_hacktoberfest2024

How'd you like that?
If you wish to add this as the new banner, I'd highly appreciate it.
Elsewise, no worries!
(Do hit me up for any changes in this, if you wish to :)

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
OMG 😱 
Its looking so good.
Can you add this to the [data](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/data) folder.

and can you change the font and make it thicker and attractive, and how will it look if the whole background is an image and text are above it?

can you change this and replace the banner in the readme and attach a screenshot in the comment 👍

**Comment by TERNION-1121** [comment]
> OMG 😱 Its looking so good. Can you add this to the [data](https://github.com/Mrinank-Bhowmick/python-beginner-projects/tree/main/data) folder.
> 
> and can you change the font and make it thicker and attractive, and how will it look if the whole background is an image and text are above it?
> 
> can you change this and replace the banner in the readme and attach a screenshot in the comment 👍

Hey @Mrinank-Bhowmick 
Thanks for waiting!

I've done the changes as you had wished for (just had to regenerate the background image to fit in the aspect ratio, thus the face and style is different)

Here's how it looks like...

image

Waiting for further response...

**Comment by Mrinank-Bhowmick** [comment]
Umm 🙄 previous one was looking much more interesting and he was so much indulged in coding that he was unaware of python snake🤣 
Can you generate some more ,and now his eyes are also closed

**Comment by TERNION-1121** [comment]
> Umm 🙄 previous one was looking much more interesting and he was so much indulged in coding that he was unaware of python snake🤣 Can you generate some more ,and now his eyes are also closed

Hey 
I tried generating several images, 
But seems like AI really needs some sleep

I got these two images, that looked like the first one

Copy of Python Beginner Projects
Copy of Python Beginner Projects (1)

Let me know if these satisfy the requirements..

**Comment by Mrinank-Bhowmick** [comment]
umm i guess first one is only looking better just work on the fonts and try to make full background img if possible ,otherwise 1st one is best

**Comment by Mrinank-Bhowmick** [comment]
You can remove my name and put the repo description there
" Explore a collection of beginner-friendly Python projects that can be completed with minimal code. Perfect for learning the basics and improving your coding skills." and I guess 2-3 hashtags will also look good at the bottom

And for the right side of the image can I get some forest-type images there in the background instead of reverting that image

**Comment by TERNION-1121** [comment]
> You can remove my name and put the repo description there " Explore a collection of beginner-friendly Python projects that can be completed with minimal code. Perfect for learning the basics and improving your coding skills." and I guess 2-3 hashtags will also look good at the bottom
> 
> And for the right side of the image can I get some forest-type images there in the background instead of reverting that image

Greetings
Here's what I've came up with...

image

**Comment by Mrinank-Bhowmick** [comment]
> > You can remove my name and put the repo description there " Explore a collection of beginner-friendly Python projects that can be completed with minimal code. Perfect for learning the basics and improving your coding skills." and I guess 2-3 hashtags will also look good at the bottom
> > 
> > And for the right side of the image can I get some forest-type images there in the background instead of reverting that image
> 
> Greetings
> Here's what I've came up with...
> 
> image

Awesome 😎
Can you add another picture in the data folder without hacktoberfest label.

**Comment by TERNION-1121** [comment]
> > > You can remove my name and put the repo description there " Explore a collection of beginner-friendly Python projects that can be completed with minimal code. Perfect for learning the basics and improving your coding skills." and I guess 2-3 hashtags will also look good at the bottom
> > > And for the right side of the image can I get some forest-type images there in the background instead of reverting that image
> > 
> > 
> > Greetings
> > Here's what I've came up with...
> > image
> 
> Awesome 😎 Can you add another picture in the data folder without hacktoberfest label.

:) Here it is:

banner-dup

**Pull request merged**
