### PR TITLE
Love Calculator, from issue #165

### PR DESCRIPTION
**Pull request by oriapp**
# Type of change 

- [x] Added new project
- [ ] Bug fix
- [x] New features 
- [x] Enhanced documentation

# Changes proposed in this pull request
Added a new game, love calculator based on the characters from the two given names.

* ### Project name : Love Calculator

* ### Short description: Takes two names from the user (as input) and calculates their match and rating.

## Checklist

- [x] The code is Python 3 compatible
- [x] I have added relevant comments in my file to make the code understandable
- [x] I have added my project to a folder that includes all the necessary files

### CODE REVIEW

**Comment by oriapp** [comment]
@Mrinank-Bhowmick could you review this one? regarding https://github.com/Mrinank-Bhowmick/python-beginner-projects/issues/165

**Comment by Mrinank-Bhowmick** [comment]
Want to add some more features to it?

**Comment by oriapp** [comment]
Like...?

**Comment by Mrinank-Bhowmick** [comment]
> Like...?

Anything that you like

**Pull request closed without merging**
