### PR TITLE
Add: Tile Master Game

### PR DESCRIPTION
**Pull request by kanchanrai7**
# Type of change 

- [X] Added new project
- [ ] Bug fix
- [] New features 
- [X] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : Tile Matching Game

* ### Short description : 
This is a tile matching game with a given time limit. The player has to match same colored tiles within 60 seconds and the player can view two tiles at time. If you like the project kindly merge it under hacktober fest!!

## Checklist

- [X] The code is Python 3 compatible
- [X] I have added relevant comments in my file to make code understandable
- [X] I have added my project in a folder which includes all the necessary files 

image

### CODE REVIEW

**Comment by kanchanrai7** [comment]
@Mrinank-Bhowmick please take a look and do let me know.

**Comment by kanchanrai7** [comment]
any updates on the review/feedback? @Mrinank-Bhowmick

**Comment by kanchanrai7** [comment]
If you do like this pls merge it under hacktoberfest.
Thanks
@Mrinank-Bhowmick

**Comment by Mrinank-Bhowmick** [comment]
Looks good to me
Thanks for contributing
Happy Hacktoberfest 🎉

**Comment by kanchanrai7** [comment]
Thank you

**Pull request merged**
