### PR TITLE
Add Python Reciept Generator

### LINKED ISSUE #199: Python Bill or Reciept generator
**Description**
A simple project to generate bills based on the inputs provided by the shopkeeper. 

***Note*** : This program will provide the customer the bill in pdf format

**Additional Info**
This project is in elementary stages and can be further improved.

### PR DESCRIPTION
**Pull request by Subha-5**
closes #199 
# Type of change 

- [X] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name :
Python Reciept Generator

* ### Short description : 
All the required information is available in the project README. 
Please take a look at it before using the program.
Complete project demonstration is included in the readme file.

### Screenshots
Screenshot from 2022-10-22 15-05-18
Screenshot from 2022-10-22 15-06-20

## Checklist

- [X] The code is Python 3 compatible
- [X] I have added relevant comments in my file to make code understandable
- [X] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Subha-5** [comment]
@Mrinank-Bhowmick please take a look and review this pull request.

**Comment by Subha-5** [comment]
@Mrinank-Bhowmick please review this issue for hacktoberfest 2022

**Comment by Subha-5** [comment]
I have updated the readme with a demonstration video of this project. Make sure to check it out.

**Comment by Mrinank-Bhowmick** [comment]
Looks awesome , thanks for contributing 
Happy hacktoberfest 🥳

**Pull request merged**
