### PR TITLE
Adding my TicTacToe project

### PR DESCRIPTION
**Pull request by Tyler-Pear**
# Type of change 

- [ X] Added new project
- [ ] Bug fix
- [ ] New features 
- [ ] Enhanced documentation

# Changes proposed in this pull request

* ### Project name : TicTacToe-TylerPear

* ### Short description : It's Tic Tac Toe. I didn't realize until I had already finished the project that someone else had already created a TicTacToe project 😂, but I would love it if anyone has any suggestions about how to make my code better!

## Checklist

- [X ] The code is Python 3 compatible
- [ X] I have added relevant comments in my file to make code understandable
- [ X] I have added my project in a folder which includes all the necessary files

### CODE REVIEW

**Comment by Mrinank-Bhowmick** [comment]
@Tyler-Pear tell me when it gets completed

**Comment by Mrinank-Bhowmick** [comment]
You don't have to edit this [README](https://github.com/Mrinank-Bhowmick/python-beginner-projects/blob/main/README.md) file, It is done automatically by a bot.

**Comment by Tyler-Pear** [comment]
@Mrinank-Bhowmick All right, thanks for the help. It should be good now.

**Comment by Mrinank-Bhowmick** [comment]
@Tyler-Pear Thanks for your contribution 🚀

**Pull request merged**
